### ISSUE TITLE
Refactor to use Dyfactor

### ISSUE THREAD

**Issue by pzuraq** [scalvert/ember-es6-class-codemod#17]
[Dyfactor](https://github.com/dyfactor/dyfactor) allows us to modify and instrument application code to gather dynamic information about an application that would be difficult or impossible to gather using static analysis alone. We can use Dyfactor to load every class in an application and gather information about them for the codemod, including:

* All of the properties and methods of the finalized class
* Which properties are computed properties
* Which methods are event listeners/observers

Using this information we can solve a few of the problems we have so far:

* **Converting `_super()` calls to `super.method()` calls.** With native classes, we can only call super _if_ the super method actually exists, whereas the old `_super()` method would fail silently. If we can lookup the finalized parent we can check if the method exists before we transform it.
* **Adding `@unobserves` and `@off` calls to overridden event listeners and observers.** We must add these decorators on _child_ classes that override methods which are decorated, and being able to lookup the parent to see if an existing observer/listener is there would be the easiest way to do that.

There will probably be other ways we can use this data as well. It should also be noted that a multipass codemod would probably _not_ be as effective as Dyfactor, due to the usage of _mixins_ in Ember. Without actually running the code, it's very difficult to determine what a finalized class with many mixins in its hierarchy would look like.

**Comment by ssutar** [comment]
The codemods are designed to accept config path parameter `runtime-config-path`. Config path must be a JSON file with data structure like 
```
{
  "data": [
    {
      "./transforms/ember-object/__testfixtures__/runtime.input.js": {
        "computedProperties": [...],
        "observedProperties": [...],
        "observerProperties": {...},
        "offProperties": [...],
        "overriddenActions": [...],
        "overriddenProperties": [...],
        "ownProperties": [...],
        "type": "EmberObject",
        "unobservedProperties": [...]
      }
    }
  ]
}
```
The [dyfactor](https://github.com/dyfactor/dyfactor) plugin to extract the runtime data is under active development currently at  [ember-es6-class-codemod-dyfactor](https://github.com/ssutar/ember-es6-class-codemod-dyfactor)
