### ISSUE TITLE
Add mixin support

### ISSUE THREAD

**Issue by pzuraq** [scalvert/ember-es6-class-codemod#4]
Currently we ignore a class definition if it supports mixins. We should be able to support this by using an intermediate extend:

```js
// before
const Foo = EmberObject.extend(MyMixin, {
  // class definition
});

// after
class Foo extends EmberObject.extend(MyMixin) {
  // class definition
}
```

**Comment by ssutar** [comment]
How would it handle the case of multiple mixins, 

```
// before
const Foo = EmberObject.extend(MixinA, MixinB, MixinC, {
  // class definition
});

// after
class Foo extends EmberObject.extend(MixinA, MixinB, MixinC) {
  // class definition
}
```

**Comment by pzuraq** [comment]
Exactly like that, the base mixins get mixed into an anonymous class, which we then extend using class syntax

**Comment by ssutar** [comment]
Fixed with https://github.com/scalvert/ember-es6-class-codemod/pull/10

**Comment by ssutar** [comment]
@pzuraq Please close this, I am not able to mark it `closed` somehow
